image: python:3.7

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - VERSION_NUMBER=${CI_COMMIT_TAG#"v"}
    - sed -i "s/<VERSION_NUMBER>/$VERSION_NUMBER/g" setup.py
    - pip install twine
    - python setup.py bdist_wheel
    - TWINE_USERNAME=__token__ TWINE_PASSWORD=$TWINE_PASSWORD python -m twine upload dist/*
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/